#!/bin/bash
adb push out/rootfs.tar.gz /sdcard
adb push bin/busybox-armv6l /cache/
adb shell 'chmod u+x /cache/busybox-armv6l'
adb shell 'make_ext4fs /dev/block/mmcblk0p4 && mount /dev/block/mmcblk0p4 /system && /cache/busybox-armv6l tar -xvf /sdcard/rootfs.tar.gz -C /system'
adb reboot-bootloader
echo "RootFS deployed - ready to boot!"
